# #checking helmfile
# helmfiles:
#   - path: ./charts/backbone-services/backboneservices-helmfile.yaml
#   - path: ./charts/core-services/coreservices-helmfile.yaml


#checking helmfile

environments:
  env:
    values:
      - ./charts/environments/env-secrets.yaml
      - ./charts/environments/env.yaml

---

helmfiles:
  - path: ./charts/backbone-services/backboneservices-helmfile.yaml
  - path: ./charts/core-services/coreservices-helmfile.yaml
#  - path: ./charts/urban/urban-helmfile.yaml           # directory does not exist in this repo
#  - path: ./charts/common-services/common-services-helmfile.yaml  # directory does not exist in this repo
#  - path: ./charts/analytics/analytics-helmfile.yaml   # directory does not exist in this repo
#  - path: ./charts/sanitation/sanitation-helmfile.yaml
  - path: ./charts/auxiliary-services/auxiliary-helmfile.yaml
#  - path: ./charts/monitoring/monitoring-helmfile.yaml
